2007-03-01  Farid Zaripov <FaridZ@kyiv.vdiweb.com>
	* 18.limits.traps.cpp (test_trap): New function to avoid MSVC error C2712:
	Cannot use __try in functions that require object unwinding;
	(test_traps) Used test_trap() function.

git-svn-id: http://svn.apache.org/repos/asf/incubator/stdcxx/trunk@513406 13f79535-47bb-0310-9956-ffa450edef68