2006-09-25  Martin Sebor  <sebor@roguewave.com>
	* scanner.cpp (convert_escape): Cast away constness to work around
	an MSVC 7.0 bug causing error C2446: '==' : no conversion from
	'char ** ' to 'const char ** ' Conversion loses qualifier.


git-svn-id: http://svn.apache.org/repos/asf/incubator/stdcxx/trunk@449774 13f79535-47bb-0310-9956-ffa450edef68